# Generated by Django 4.2.6 on 2023-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('rate', models.FloatField(null=True)),
                ('property_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('host_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('accommodates', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('guests_included', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('beds', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('space', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('number_of_reviews', models.IntegerField(blank=True, null=True)),
                ('smart_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture_url', models.JSONField()),
                ('amenities', models.JSONField(null=True)),
            ],
        ),
    ]
