# Generated by Django 4.2.6 on 2023-10-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.FloatField()),
                ('property_type', models.CharField(blank=True, default='', max_length=100)),
                ('host_name', models.CharField(blank=True, default='', max_length=100)),
                ('room_type', models.CharField(blank=True, default='', max_length=100)),
                ('accommodates', models.CharField(blank=True, default='', max_length=100)),
                ('guests_included', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('space', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('smart_location', models.CharField(blank=True, default='', max_length=100)),
                ('picture_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.picture')),
            ],
        ),
    ]
