# Generated by Django 4.2.6 on 2023-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='accommodates',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='guests_included',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='smart_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='space',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
