# Generated by Django 4.2.6 on 2023-10-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_item_hotel_number_of_reviews_hotel_amenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Amenitie',
        ),
    ]
