# Generated by Django 4.2.6 on 2023-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_hotel_amenities_amenitie_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitie',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
