# Generated by Django 4.2.6 on 2023-10-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_amenitie_amenitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitie',
            name='amenitie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
