# Generated by Django 4.2.6 on 2023-10-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_amenitie_amenitie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.contact')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.department')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='picture_url',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Amenitie',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
